/**
 * Auto-generated TypeScript declarations for MCP tools
 * Generated: 2025-09-30T12:00:00.000Z
 *
 * This file provides type-safe access to all MCP server tools
 * available in the codemode-unified execution environment.
 *
 * DO NOT EDIT THIS FILE MANUALLY - it will be regenerated automatically
 * when MCP servers are initialized.
 *
 * @packageDocumentation
 */

/**
 * Result type for MCP tool calls
 *
 * All MCP tools return a Promise that resolves to this structure.
 * The content array can contain text, image, or resource elements.
 */
interface MCPToolResult {
  /** Array of content items returned by the tool */
  content: Array<{
    /** Type of content (text, image, or resource) */
    type: 'text' | 'image' | 'resource';
    /** Text content (present when type is "text") */
    text?: string;
    /** Base64-encoded binary data (present when type is "image") */
    data?: string;
    /** MIME type of the content */
    mimeType?: string;
    /** Resource URI (present when type is "resource") */
    uri?: string;
  }>;
  /** Whether the tool call resulted in an error */
  isError?: boolean;
  /** Error message if isError is true */
  errorMessage?: string;
}

/** Generated from automem.store_memory schema */
interface AutomemStoreMemoryArgs {
  /** Memory content to store */
  content: string;
  /** Optional tags to categorize the memory */
  tags?: string[];
  /** Importance score between 0 and 1 */
  importance?: number;
  /** Optional metadata payload */
  metadata?: Record<string, unknown>;
  /** Optional ISO timestamp */
  timestamp?: string;
  /** Optional embedding vector for semantic search */
  embedding?: number[];
}

/** Generated from automem.recall_memory schema */
interface AutomemRecallMemoryArgs {
  /** Text query to search for in memory content */
  query?: string;
  /** Embedding vector for semantic similarity search */
  embedding?: number[];
  /** Maximum number of memories to return */
  limit?: number;
  /** Return memories containing any of these tags */
  tags?: string[];
  /** Natural language time window (e.g. "today", "last week") */
  time_query?: string;
  /** Explicit ISO timestamp lower bound */
  start?: string;
  /** Explicit ISO timestamp upper bound */
  end?: string;
}

/** Generated from context7.resolve-library-id schema */
interface Context7ResolveLibraryIdArgs {
  /** Library name to search for and retrieve a Context7-compatible library ID */
  libraryName: string;
}

declare global {
  const mcp: {
    /**
     * MCP Server: automem
     * 2 tools available
     */
    automem: {
      /**
       * Store a memory with optional tags, importance score, metadata,
       * timestamps, and embedding vector
       */
      store_memory(args: AutomemStoreMemoryArgs): Promise<MCPToolResult>;

      /**
       * Recall memories with hybrid semantic/keyword search and optional
       * time/tag filters
       */
      recall_memory(args: AutomemRecallMemoryArgs): Promise<MCPToolResult>;
    };

    /**
     * MCP Server: context7
     * 1 tool available
     */
    context7: {
      /**
       * Resolves a package/product name to a Context7-compatible library ID
       * and returns a list of matching libraries
       */
      'resolve-library-id'(
        args: Context7ResolveLibraryIdArgs
      ): Promise<MCPToolResult>;
    };
  };
}

export {};